services:
  db:
    build:
      context: ./src/
      dockerfile: ./dockerfiles/main_postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  postgres:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: ${AF_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AF_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AF_POSTGRES_DB}
    ports:
      - "5433:5433"
    command: ["postgres", "-p", "5433"]

  airflow:
    build:
      context: ./src/
      dockerfile: ./dockerfiles/airflow
    container_name: airflow_webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AF_POSTGRES_USER}:${AF_POSTGRES_PASSWORD}@postgres:5433/${AF_POSTGRES_DB}
      AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: 'false'
      AF_USER: ${AF_USER}
      AF_PASS: ${AF_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      REDSHIFT_HOST: ${REDSHIFT_HOST}
      REDSHIFT_DB: ${REDSHIFT_DB}
      REDSHIFT_USER: ${REDSHIFT_USER}
      REDSHIFT_PASSWORD: ${REDSHIFT_PASSWORD}
    ports:
      - "8080:8080"
    entrypoint: ["sh", "-c"]
    command: ["./entrypoint.sh"]

  fastapi:
    build:
      context: ./src/
      dockerfile: ./dockerfiles/fastapi
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      HOST: db
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: "us-east-1"
    ports:
      - "8000:8000"
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]

  jupyterlab_instance:
    build:
      context: ./src
      dockerfile: ./dockerfiles/jupyterlab
    container_name: jupyterlab_instance
    ports:
      - "8889:8889"
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      REDSHIFT_HOST: ${REDSHIFT_HOST}
      REDSHIFT_DB: ${REDSHIFT_DB}
      REDSHIFT_USER: ${REDSHIFT_USER}
      REDSHIFT_PASSWORD: ${REDSHIFT_PASSWORD}
    entrypoint: [ "sh", "-c" ]
    command: ["./entrypoint.sh"]
